// Mocks generated by Mockito 5.4.4 from annotations
// in quizator/test/features/quiz/data/repositories/quiz_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quizator/core/helpers/network_info.dart' as _i8;
import 'package:quizator/features/quiz/data/datasources/quiz_netwok_data_source.dart'
    as _i6;
import 'package:quizator/features/quiz/data/models/quiz_model.dart' as _i4;
import 'package:quizator/features/quiz/data/services/quiz_service.dart' as _i3;
import 'package:quizator/services/log/my_logger.dart' as _i5;
import 'package:talker_flutter/talker_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTalker_0 extends _i1.SmartFake implements _i2.Talker {
  _FakeTalker_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizService_1 extends _i1.SmartFake implements _i3.QuizService {
  _FakeQuizService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuizModel_2 extends _i1.SmartFake implements _i4.QuizModel {
  _FakeQuizModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MyTalkerLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyTalkerLogger extends _i1.Mock implements _i5.MyTalkerLogger {
  @override
  _i2.Talker get talker => (super.noSuchMethod(
        Invocation.getter(#talker),
        returnValue: _FakeTalker_0(
          this,
          Invocation.getter(#talker),
        ),
        returnValueForMissingStub: _FakeTalker_0(
          this,
          Invocation.getter(#talker),
        ),
      ) as _i2.Talker);

  @override
  void debug(String? message) => super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(String? message) => super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handle(
    Object? exception, [
    StackTrace? stackTrace,
    dynamic msg,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #handle,
          [
            exception,
            stackTrace,
            msg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message) => super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void verbose(String? message) => super.noSuchMethod(
        Invocation.method(
          #verbose,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message) => super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuizNetworkDataSource].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockQuizNetworkDataSource extends _i1.Mock
    implements _i6.QuizNetworkDataSource {
  @override
  _i3.QuizService get quizService => (super.noSuchMethod(
        Invocation.getter(#quizService),
        returnValue: _FakeQuizService_1(
          this,
          Invocation.getter(#quizService),
        ),
        returnValueForMissingStub: _FakeQuizService_1(
          this,
          Invocation.getter(#quizService),
        ),
      ) as _i3.QuizService);

  @override
  _i7.Future<_i4.QuizModel> getSelectedQuiz({required int? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedQuiz,
          [],
          {#category: category},
        ),
        returnValue: _i7.Future<_i4.QuizModel>.value(_FakeQuizModel_2(
          this,
          Invocation.method(
            #getSelectedQuiz,
            [],
            {#category: category},
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.QuizModel>.value(_FakeQuizModel_2(
          this,
          Invocation.method(
            #getSelectedQuiz,
            [],
            {#category: category},
          ),
        )),
      ) as _i7.Future<_i4.QuizModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  @override
  _i7.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}
