// Mocks generated by Mockito 5.4.4 from annotations
// in quizator/test/features/quiz/data/datasources/quiz_netwok_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chopper/chopper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:quizator/features/quiz/data/models/quiz_model.dart' as _i6;
import 'package:quizator/features/quiz/data/services/quiz_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuizService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizService extends _i1.Mock implements _i2.QuizService {
  @override
  _i3.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.ChopperClient);

  @override
  set client(_i3.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
        returnValueForMissingStub: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);

  @override
  _i5.Future<_i3.Response<_i6.QuizModel>> getSelectedQuiz(
    int? category, {
    int? amount = 10,
    String? type = r'multi',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedQuiz,
          [category],
          {
            #amount: amount,
            #type: type,
          },
        ),
        returnValue: _i5.Future<_i3.Response<_i6.QuizModel>>.value(
            _i4.dummyValue<_i3.Response<_i6.QuizModel>>(
          this,
          Invocation.method(
            #getSelectedQuiz,
            [category],
            {
              #amount: amount,
              #type: type,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<_i6.QuizModel>>.value(
                _i4.dummyValue<_i3.Response<_i6.QuizModel>>(
          this,
          Invocation.method(
            #getSelectedQuiz,
            [category],
            {
              #amount: amount,
              #type: type,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<_i6.QuizModel>>);
}
